In [7]:
import numpy as np
from numpy import genfromtxt

In [10]:
data=genfromtxt('../DATA/bank_note_data.txt',delimiter=',')


In [11]:
data

array([[  3.6216 ,   8.6661 ,  -2.8073 ,  -0.44699,   0.     ],
       [  4.5459 ,   8.1674 ,  -2.4586 ,  -1.4621 ,   0.     ],
       [  3.866  ,  -2.6383 ,   1.9242 ,   0.10645,   0.     ],
       ...,
       [ -3.7503 , -13.4586 ,  17.5932 ,  -2.7771 ,   1.     ],
       [ -3.5637 ,  -8.3827 ,  12.393  ,  -1.2823 ,   1.     ],
       [ -2.5419 ,  -0.65804,   2.6842 ,   1.1952 ,   1.     ]])

In [12]:
labels=data[:,4]
#use of this is to get the labels of the data and store it in the labels variable that will be used later on in the code for the training and testing of the data as our label variables tell use about the class of the data and we have used ,4 in the columns so as to get the 4th column of the data as the labels of the data

In [13]:
labels

array([0., 0., 0., ..., 1., 1., 1.])

In [14]:
features=data[:,0:4]


In [15]:
X=features
y=labels

In [16]:
from sklearn.model_selection import train_test_split


In [17]:
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.30,random_state=42)

In [19]:
len(X_train)

960

In [20]:
y_train

array([1., 1., 0., 1., 0., 1., 0., 0., 0., 1., 1., 0., 0., 0., 1., 0., 0.,
       1., 0., 0., 0., 0., 1., 0., 1., 0., 0., 1., 0., 0., 0., 0., 0., 0.,
       1., 1., 0., 0., 0., 0., 0., 1., 1., 0., 1., 0., 0., 1., 0., 0., 1.,
       0., 0., 0., 1., 1., 1., 0., 1., 1., 1., 0., 1., 1., 1., 0., 1., 0.,
       0., 1., 0., 0., 0., 1., 0., 1., 0., 0., 0., 0., 1., 1., 0., 0., 1.,
       0., 0., 1., 1., 1., 0., 0., 0., 1., 1., 1., 1., 1., 1., 1., 0., 0.,
       0., 0., 0., 0., 1., 0., 1., 0., 0., 0., 0., 1., 1., 0., 1., 1., 0.,
       1., 0., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 0., 1., 0., 0.,
       0., 0., 1., 1., 1., 0., 0., 0., 1., 0., 1., 1., 1., 1., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 1., 0., 1., 0., 1., 0.,
       0., 0., 0., 0., 1., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       1., 1., 0., 1., 0., 0., 1., 1., 0., 1., 0., 0., 1., 0., 1., 1., 0.,
       0., 0., 0., 0., 0., 1., 0., 0., 0., 1., 1., 0., 1., 1., 1., 1., 1.,
       0., 1., 1., 0., 0.

In [21]:
from sklearn.preprocessing import MinMaxScaler

In [22]:
scaler_object=MinMaxScaler()


In [24]:
scaler_object.fit(X_train)

MinMaxScaler()

In [26]:
scaled_X_train=scaler_object.transform(X_train)

In [42]:
scaled_X_test=scaler_object.transform(X_test)

In [28]:
scaled_X_train.max()

1.0000000000000002

In [33]:
!pip install keras

Defaulting to user installation because normal site-packages is not writeable


DEPRECATION: Loading egg at c:\program files\python311\lib\site-packages\vboxapi-1.0-py3.11.egg is deprecated. pip 24.3 will enforce this behaviour change. A possible replacement is to use pip for package installation.. Discussion can be found at https://github.com/pypa/pip/issues/12330

[notice] A new release of pip is available: 23.3.2 -> 24.2
[notice] To update, run: python.exe -m pip install --upgrade pip


In [34]:
!pip install tensorflow

Defaulting to user installation because normal site-packages is not writeable


DEPRECATION: Loading egg at c:\program files\python311\lib\site-packages\vboxapi-1.0-py3.11.egg is deprecated. pip 24.3 will enforce this behaviour change. A possible replacement is to use pip for package installation.. Discussion can be found at https://github.com/pypa/pip/issues/12330

[notice] A new release of pip is available: 23.3.2 -> 24.2
[notice] To update, run: python.exe -m pip install --upgrade pip


In [36]:
from keras.models import Sequential
from keras.layers import Dense

In [38]:
model=Sequential()

model.add(Dense(4,input_dim=4,activation='relu'))
model.add(Dense(8,activation='relu'))
model.add(Dense(1,activation='sigmoid'))

C:\Users\HP\AppData\Roaming\Python\Python311\site-packages\keras\src\layers\core\dense.py:87: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)


In [39]:
model.compile(loss='binary_crossentropy',optimizer='adam',metrics=['accuracy'])

In [40]:
model.fit(scaled_X_train,y_train,epochs=50,verbose=2)

Epoch 1/50
30/30 - 1s - 46ms/step - accuracy: 0.5552 - loss: 0.6831
Epoch 2/50
30/30 - 0s - 3ms/step - accuracy: 0.5552 - loss: 0.6747
Epoch 3/50
30/30 - 0s - 4ms/step - accuracy: 0.5552 - loss: 0.6688
Epoch 4/50
30/30 - 0s - 3ms/step - accuracy: 0.5552 - loss: 0.6634
Epoch 5/50
30/30 - 0s - 3ms/step - accuracy: 0.5552 - loss: 0.6584
Epoch 6/50
30/30 - 0s - 2ms/step - accuracy: 0.5552 - loss: 0.6531
Epoch 7/50
30/30 - 0s - 2ms/step - accuracy: 0.5552 - loss: 0.6475
Epoch 8/50
30/30 - 0s - 2ms/step - accuracy: 0.5646 - loss: 0.6413
Epoch 9/50
30/30 - 0s - 2ms/step - accuracy: 0.5708 - loss: 0.6346
Epoch 10/50
30/30 - 0s - 4ms/step - accuracy: 0.5865 - loss: 0.6265
Epoch 11/50
30/30 - 0s - 2ms/step - accuracy: 0.6219 - loss: 0.6159
Epoch 12/50
30/30 - 0s - 3ms/step - accuracy: 0.6979 - loss: 0.5921
Epoch 13/50
30/30 - 0s - 2ms/step - accuracy: 0.7802 - loss: 0.5594
Epoch 14/50
30/30 - 0s - 2ms/step - accuracy: 0.7896 - loss: 0.5353
Epoch 15/50
30/30 - 0s - 3ms/step - accuracy: 0.7937 - l

In [43]:
scaled_X_test

array([[0.62098955, 0.75284662, 0.21900753, 0.5730998 ],
       [0.48778602, 0.82175665, 0.09174727, 0.56211079],
       [0.51158363, 0.77924916, 0.13830875, 0.50392598],
       ...,
       [0.51963164, 0.38970316, 0.28618249, 0.92478549],
       [0.68099575, 0.57607382, 0.35760953, 0.86502189],
       [0.72424262, 0.73286884, 0.13069728, 0.73596217]])

In [45]:
import numpy as np

# Use model.predict() and then take the class with the highest probability
predictions = model.predict(scaled_X_test)
predicted_classes = np.argmax(predictions, axis=1)  # Returns the index of the highest probability

print(predicted_classes)


13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step
[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0]


In [46]:
model.metrics_names

['loss', 'compile_metrics']

In [47]:
from sklearn.metrics import confusion_matrix,classification_report

In [49]:
predictions=model.predict(scaled_X_test)

13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step 


In [50]:
confusion_matrix(y_test,predicted_classes)

array([[229,   0],
       [183,   0]], dtype=int64)

In [52]:
print(classification_report(y_test,predictions))

ValueError: Classification metrics can't handle a mix of binary and continuous targets

In [53]:
model.save('mymodel.h5')

In [54]:
from keras.models import load_model

In [55]:
newmodel=load_model('mymodel.h5')

In [56]:
newmodel.predict(scaled_X_test)

13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step


array([[0.06003527],
       [0.47054327],
       [0.2942357 ],
       [0.07744654],
       [0.05295437],
       [0.02620121],
       [0.20608775],
       [0.01196012],
       [0.04566819],
       [0.1383387 ],
       [0.5574671 ],
       [0.8863345 ],
       [0.17710724],
       [0.8360245 ],
       [0.605271  ],
       [0.30649698],
       [0.9235195 ],
       [0.93098366],
       [0.89358354],
       [0.8603027 ],
       [0.02881108],
       [0.08766232],
       [0.8779049 ],
       [0.02024198],
       [0.97925717],
       [0.02484692],
       [0.01362213],
       [0.88132167],
       [0.00164539],
       [0.00343053],
       [0.77195317],
       [0.11654175],
       [0.17881525],
       [0.97427726],
       [0.96768785],
       [0.01088921],
       [0.52695274],
       [0.8234452 ],
       [0.9015495 ],
       [0.0995913 ],
       [0.06274305],
       [0.7658559 ],
       [0.8263705 ],
       [0.03596996],
       [0.9763323 ],
       [0.8809889 ],
       [0.9557966 ],
       [0.042